### PR TITLE
use system property to get OH2 userdir

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by cdjackson** [comment]
Sorry - I should have read all the emails :)  I assume this works with OH1 but will check…

Thanks

**Comment by maggu2810** [comment]
You have it written yourself instead of using the PR bc3315084078646e532fa593c1c4f14ad73e5557
Should I close this one?

**Comment by cdjackson** [comment]
Ah - sorry - I was just reading on Git and it kooked like youd just pasted in the code as a comment...

Yes, you might as well close.

Thanks again (and sorry again)

Chris

Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Markus Rathgeb <notifications@github.com> </div><div>Date:17/02/2015  07:12  (GMT+00:00) </div><div>To: cdjackson/openhab <openhab@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [openhab] use system property to get OH2 userdir (#11) </div><div>
</div>You have it written yourself instead of using the PR bc33150
Should I close this one?

**Comment by cdjackson** [comment]
Sorry - I'll close this - I didn't realise it was sent as a PR and I got confused with the comments you made in the issue.
Thanks :)

**Pull request closed without merging**
