### PR TITLE
Add linear garage controller

### PR DESCRIPTION
**Pull request by jhuizingh**
Attempting to add a new zwave item for a Linear garage door opener controller.

Please verify that this looks ok as this is my first attempt at doing this.

Details here: http://www.pepper1.net/zwavedb/device/684
File eco/tiltzwave2.xml used as an example

Sorry that it's trying to pull 9 commits. I can't figure out why it's not just pulling my one commit on this branch...

### CODE REVIEW

**Comment by cdjackson** [comment]
Hi,
Thanks for the PR. Can I ask you to resubmit this against the openhab master repository?

What you should do is the following -:
Clone the openhab main repository. Copy over the ndg00z.xml and the corresponding part of the products.xml file. then create a PR into the main openhab repository.  It's easier to merge it direct to there...

Thanks
Chris

**Comment by jhuizingh** [comment]
Absolutely. Thanks!

**Comment by jhuizingh** [comment]
Done!

**Comment by cdjackson** [comment]
Thanks - all merged.

**Pull request closed without merging**
