### PR TITLE
Zwave product database entries for two Devolo devices

### PR DESCRIPTION
**Pull request by stevensmi**
Devolo resells a number of Z-Wave devices. In this case a Danfoss theromstat and a Vision smoke detector.
The Danfoss theromstat has kept it manufacture id but has a no device reference.
The Vison smoke detector has been given the Devolo manufacture id.

In both cases the products.xml has a new entry for the device which simply reference the OEM ConfigFile.

### CODE REVIEW

**Comment by cdjackson** [comment]
This PR includes a lot of stuff that's unrelated (41 commits and 98 files modified!). Please can you resolve this and request the PR on the main openHAB repository.

**Comment by stevensmi** [comment]
Wilco

**Comment by stevensmi** [comment]
OK now the pull request is based against the correct repos!

Pull request is #4098 in openhab/opnehab

**Comment by cdjackson** [comment]
Thanks - looks good. I’ll take a look at them later or tomorrow morning.

Cheers
Chris

**Pull request closed without merging**
